-- MySQL Script generated by MySQL Workbench
-- Sat May  6 12:50:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema visitapp_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema visitapp_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `visitapp_db` DEFAULT CHARACTER SET utf8 ;
USE `visitapp_db` ;

-- -----------------------------------------------------
-- Table `visitapp_db`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Usuario` (
  `rut` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `rol` TINYINT NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Jefe_hogar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Jefe_hogar` (
  `rut` VARCHAR(45) NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `edad` INT NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `nacionalidad` VARCHAR(45) NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Visita` (
  `id` INT NOT NULL,
  `motivo` VARCHAR(45) NOT NULL,
  `Usuario_rut` INT NOT NULL,
  PRIMARY KEY (`id`, `Usuario_rut`),
  CONSTRAINT `fk_Visita_Usuario`
    FOREIGN KEY (`Usuario_rut`)
    REFERENCES `visitapp_db`.`Usuario` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Hogar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Hogar` (
  `id_hogar` INT NOT NULL,
  `situacion_familiar` VARCHAR(150) NOT NULL,
  `situacion_vivienda` VARCHAR(150) NOT NULL,
  `relaciones_sociales` VARCHAR(150) NULL,
  `beneficios_estatales` VARCHAR(45) NULL,
  `Visita_id` INT NOT NULL,
  `Visita_Usuario_rut` INT NOT NULL,
  `Jefe_hogar_rut` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_hogar`, `Visita_id`, `Visita_Usuario_rut`, `Jefe_hogar_rut`),
  CONSTRAINT `fk_Hogar_Visita1`
    FOREIGN KEY (`Visita_id` , `Visita_Usuario_rut`)
    REFERENCES `visitapp_db`.`Visita` (`id` , `Usuario_rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Hogar_Jefe_hogar1`
    FOREIGN KEY (`Jefe_hogar_rut`)
    REFERENCES `visitapp_db`.`Jefe_hogar` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Integrante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Integrante` (
  `rut` INT NOT NULL,
  `nombre_completo` VARCHAR(100) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `edad` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NULL,
  `nivel_educacional` VARCHAR(45) NULL,
  `ocupacion` VARCHAR(45) NOT NULL,
  `Hogar_id_hogar` INT NOT NULL,
  PRIMARY KEY (`rut`, `Hogar_id_hogar`),
  CONSTRAINT `fk_Integrante_Hogar1`
    FOREIGN KEY (`Hogar_id_hogar`)
    REFERENCES `visitapp_db`.`Hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Situacion_salud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Situacion_salud` (
  `rut` VARCHAR(45) NOT NULL,
  `nombre_completo` VARCHAR(60) NOT NULL,
  `tipo_enfermedad` VARCHAR(45) NOT NULL,
  `discapacidad` VARCHAR(45) NOT NULL,
  `observacion` VARCHAR(150) NULL,
  `Hogar_id_hogar` INT NOT NULL,
  PRIMARY KEY (`rut`, `Hogar_id_hogar`),
  CONSTRAINT `fk_Situacion_salud_Hogar1`
    FOREIGN KEY (`Hogar_id_hogar`)
    REFERENCES `visitapp_db`.`Hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Situacion_economica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Situacion_economica` (
  `rut` INT NOT NULL,
  `nombre_completo` VARCHAR(45) NOT NULL,
  `ingresos` INT NOT NULL,
  `tipo_empleo` VARCHAR(45) NOT NULL,
  `desempleo` VARCHAR(45) NULL,
  `prevision` VARCHAR(45) NOT NULL,
  `Hogar_id_hogar` INT NOT NULL,
  PRIMARY KEY (`rut`, `Hogar_id_hogar`),
  CONSTRAINT `fk_Situacion_economica_Hogar1`
    FOREIGN KEY (`Hogar_id_hogar`)
    REFERENCES `visitapp_db`.`Hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Gastos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Gastos` (
  `gastos_basicos` INT NOT NULL,
  `alimentacion` INT NOT NULL,
  `vestimenta` INT NOT NULL,
  `higiene` INT NOT NULL,
  `colegiatura` INT NOT NULL,
  `dividendo` INT NOT NULL,
  `gastos_medicos` INT NOT NULL,
  `otros` INT NOT NULL,
  `Hogar_id_hogar` INT NOT NULL,
  PRIMARY KEY (`Hogar_id_hogar`),
  CONSTRAINT `fk_Gastos_Hogar1`
    FOREIGN KEY (`Hogar_id_hogar`)
    REFERENCES `visitapp_db`.`Hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Necesidades_espirituales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Necesidades_espirituales` (
  `bendicion_casa` TINYINT NULL,
  `bautismo` TINYINT NULL,
  `uncion_enfermos` TINYINT NULL,
  `primera_comunion` TINYINT NULL,
  `confirmacion` TINYINT NULL,
  `Hogar_id_hogar` INT NOT NULL,
  PRIMARY KEY (`Hogar_id_hogar`),
  CONSTRAINT `fk_Necesidades_espirituales_Hogar1`
    FOREIGN KEY (`Hogar_id_hogar`)
    REFERENCES `visitapp_db`.`Hogar` (`id_hogar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `visitapp_db`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `visitapp_db`.`Historial` (
  `fecha` DATE NOT NULL,
  `Usuario_rut` INT NOT NULL,
  PRIMARY KEY (`Usuario_rut`),
  CONSTRAINT `fk_Historial_Usuario1`
    FOREIGN KEY (`Usuario_rut`)
    REFERENCES `visitapp_db`.`Usuario` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
